sizeof: 
	gcc -o boutef sizeoftest.c -Wall
runsizeof:
	./boutef 
plusun: 
	gcc -o mohvi plusunalgo.c -Wall
runplusun:
	./mohvi
tablo:
	gcc -o macron tableaux.c -Wall
runtablo:
	./macron
b_t_t_f:
	gcc -o trump back_to_the_file.c -Wall
runb_t_t_f:
	./trump nombres_uniques.data
